package com.vimeo.sample;

import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.google.gson.reflect.TypeToken;
import com.vimeo.sample.model.OuterClassWithInnerModel;
import com.vimeo.sample.stag.generated.Stag;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class OuterClassWithInnerModelTest {

    @Test
    public void typeAdapterWasGenerated() throws Exception {
        Gson gson = new Gson();
        Stag.Factory factory = new Stag.Factory();
        TypeToken<OuterClassWithInnerModel.InnerModel> innerModelType =
                TypeToken.get(OuterClassWithInnerModel.InnerModel.class);
        TypeAdapter<OuterClassWithInnerModel.InnerModel> adapter = factory.create(gson, innerModelType);
        assertNotNull("Type adapter was not generated by Stag", adapter);
    }

}
