# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.3"

default_platform :android

platform :android do
  before_all do
    if is_ci then
      ENV['GRADLE_OPTS'] = [
        "-Dorg.gradle.daemon=false",
        "-Dorg.gradle.full-stacktrace=true"
        ].join(",")
    end
    if not ENV['ANDROID_HOME']
      ENV['ANDROID_HOME'] = File.expand_path("~/Library/Android/sdk")
    end
  end

  desc "main entrypoint for CI"
  lane :shipit do
    if is_ci
      # If the build was triggered by a Pull Request
      if ENV['TRAVIS_PULL_REQUEST'] && ENV['TRAVIS_PULL_REQUEST'] != 'false'
        test
      else
        # This build was triggered by a branch update
        branch = git_branch
        # If the branch is master, this means new updates were merged into master
        # Then publish the artifacts to bintray
        if branch == 'master'
          publish_artifacts(
            snapshot: false
          )

          # TODO: publish Snapshots with snapshot = true
        end
      end
    end
  end

  desc "publish artifacts to bintray. Use the 'snapshot' option (boolean) to publish a Snapshot instead of a release (not implemented yet)"
  lane :publish_artifacts do |options|
    # Upload to bintray
    gradle(
      task: "stag-library:bintrayUpload stag-library-compiler:bintrayUpload",
      properties: {
        "snapshot" => options[:snapshot]
      }
    )
  end

  desc "test"
  lane :test do
    
  # run the tests, but dont puke everywhere until the report is printed.
  junit_report_path_array = [
    "stag-library/build/test-results/test/*.xml",
    "stag-library-compiler/build/test-results/test/*.xml",
    "integration-test-java/build/test-results/test/*.xml",
    "integration-test-java-cross-module/build/test-results/test/*.xml",
    "integration-test-kotlin/build/test-results/testDebugUnitTest/*.xml",
    "sample/build/test-results/testDebugUnitTest/*.xml",
    "integration-test-android/build/test-results/testDebugUnitTest/*.xml"
  ]
  begin
    gradle(
      task: "stag-library:test stag-library-compiler:test sample:test integration-test-java:test integration-test-java-cross-module:test integration-test-kotlin:test integration-test-android:test"
    )
  rescue => error
  begin
    junit_report_path_array.each { |path| pretty_junit(file_pattern: path) }
  rescue => error
  end

  if is_ci && ENV['DANGER_GITHUB_API_TOKEN']
    danger(use_bundle_exec: false)
  end

  raise error
  end

  begin
    junit_report_path_array.each { |path| pretty_junit(file_pattern: path) }
  rescue => error
  end

  if is_ci && ENV['DANGER_GITHUB_API_TOKEN']
    danger(use_bundle_exec: false)
  end


  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
