# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.3"

default_platform :android

platform :android do
  before_all do
    if is_ci then
      ENV['GRADLE_OPTS'] = [
        "-Dorg.gradle.daemon=false",
        "-Dorg.gradle.full-stacktrace=true"
        ].join(",")
    end
    if not ENV['ANDROID_HOME']
      ENV['ANDROID_HOME'] = File.expand_path("~/Library/Android/sdk")
    end
  end

  desc "test"
  lane :test do
    
    # gotta do some setup before running gradle
    sh 'touch ../local.properties'

    gradle(
        task: "stag-library:build stag-library-compiler:build sample:build"
    )
    pretty_junit(file_pattern: "stag-library-compiler/build/test-results/TEST-*")

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
