# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.3"

default_platform :android

platform :android do
  before_all do
    if is_ci then
      ENV['GRADLE_OPTS'] = [
        "-Dorg.gradle.daemon=false",
        "-Dorg.gradle.full-stacktrace=true"
        ].join(",")
    end
    if not ENV['ANDROID_HOME']
      ENV['ANDROID_HOME'] = File.expand_path("~/Library/Android/sdk")
    end
  end

  desc "test"
  lane :test do
    
  # gotta do some setup before running gradle
  sh 'touch ../local.properties'

  # run the tests, but dont puke everywhere until the report is printed.
  junit_report_path_array = [
    "stag-library/build/test-results/test/*.xml",
    "stag-library-compiler/build/test-results/test/*.xml",
    "sample-java-model/build/test-results/test/*.xml",
    "sample-kotlin-model/build/test-results/testDebugUnitTest/*.xml",
    "sample/build/test-results/testDebugUnitTest/*.xml",
    "sample-model/build/test-results/testDebugUnitTest/*.xml"
  ]
  begin
    gradle(
      task: "sample:build stag-library:test stag-library-compiler:test sample:test sample-model:test sample-java-model:test sample-kotlin-model:test"
    )
  rescue => error
  begin
    junit_report_path_array.each { |path| pretty_junit(file_pattern: path) }
  rescue => error
  end

  if is_ci && ENV['DANGER_GITHUB_API_TOKEN']
    danger(use_bundle_exec: false)
  end

  raise error
  end

  begin
    junit_report_path_array.each { |path| pretty_junit(file_pattern: path) }
  rescue => error
  end

  if is_ci && ENV['DANGER_GITHUB_API_TOKEN']
    danger(use_bundle_exec: false)
  end


  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

  end

  error do |lane, exception|

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
